name: Build

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-native:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        arch: [x86, x86_64, arm32, arm64]
        exclude:
          - os: macos-latest
            arch: x86
          - os: macos-latest
            arch: arm32

    steps:
      - name: Fetch sources
        uses: actions/checkout@v5

      - name: Install Linux dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake build-essential

      - name: Install Windows dependencies
        if: runner.os == 'Windows'
        shell: pwsh
        run: choco install ninja cmake -y

      - name: Install macOS dependencies
        if: runner.os == 'macos'
        run: brew install ninja cmake

      - name: Configure CMake
        run: |
          cmake -S ${{ github.workspace }}/src/main/cpp -B ${{ github.workspace }}/build/.cxx/${{ matrix.os }}/${{ matrix.arch }} \
            -DCMAKE_BUILD_TYPE=RelWithDebugInfo \
            ${{ matrix.os == 'macos-latest' && format('-DCMAKE_OSX_ARCHITECTURES={0}', matrix.arch == 'x86' && 'x86_64' || matrix.arch) || '' }} \
            ${{ matrix.os == 'windows-latest' && (matrix.arch == 'x86' && '-A Win32' || matrix.arch == 'x86_64' && '-A x64' || '') || '' }}

      - name: Build C++ Code
        run: cmake --build ${{ github.workspace }}/build/.cxx/${{ matrix.os }}/${{ matrix.arch }} --config=RelWithDebugInfo

      - name: Collect Native Libs
        run: |
          mkdir -p artifacts
          OS=$(echo "${{ matrix.os }}" | sed 's/-latest//')
          for f in $(find build/${{ matrix.os }}/${{ matrix.arch }} -type f \( -name "*.so" -o -name "*.dll" -o -name "*.dylib" \)); do
            base=$(basename "$f")
            ext="${base##*.}"
            name="${base%.*}"
            cp "$f" "artifacts/${name}_${OS}_${{ matrix.arch }}.${ext}"
          done
        shell: bash

      - name: Upload native artifacts
        uses: actions/upload-artifact@v4
        with:
          name: native-libs-${{ matrix.os }}-${{ matrix.arch }}
          path: artifacts/

  build-java:
    runs-on: ubuntu-latest
    needs: build-native
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Download native artifacts
        uses: actions/download-artifact@v5
        with:
          path: native-artifacts
          merge-multiple: true

      - name: Copy native libs into Java resources
        run: |
          mkdir -p src/main/resources/native
          cp -r native-artifacts/* src/main/resources/native/

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Java project
        run: ./gradlew clean fatJar -PoffBuildLibs=true

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          path: build/libs/*.jar

      - name: Extract version
        run: |
          VERSION=$(sed -nE 's/^version = "([0-9\.]+)".*\/\/ CI_PROJECT_VERSION/\1/p' build.gradle.kts)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "VERSION = $VERSION"

      - name: Create Draft Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v${{ env.VERSION }}" \
            --draft \
            --title "v${{ env.VERSION }}" \
            build/libs/*.jar
